spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/moviegenie
    username: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

server:
  servlet:
    session:
      timeout: 60

logging:
  level:
    org.hibernate:
      SQL: debug
